import { z } from "zod";

const StopSchema = z.object({
  evaNumber: z.string(),
  name: z.string(),
  canceled: z.boolean(),
});

const EntrySchema = z.object({
  canceledStopsAfterActualDestination: z.array(StopSchema),
  direction: z.string(),
  id: z.string(),
  timeSchedule: z.string(),
  timeDelayed: z.string(),
  delayed: z.boolean(),
  platform: z.string(),
  platformSchedule: z.string(),
  timeType: z.string(),
  canceled: z.boolean(),
  administrationID: z.string(),
  virtual: z.boolean(),
  lineName: z.string(),
  type: z.string(),
  kind: z.string(),
  journeyID: z.string(),
  stopPlace: StopSchema,
  arrivalOrDepartureId: z.string(),
  destination: z.object({
    evaNumber: z.string(),
    name: z.string(),
    canceled: z.boolean(),
    slug: z.string().optional(),
    nameParts: z
      .array(
        z.object({
          type: z.string(),
          value: z.string(),
          valueSpeech: z.string().optional(),
        }),
      )
      .optional(),
  }),
  viaStops: z.array(
    z.object({
      evaNumber: z.string(),
      name: z.string(),
      canceled: z.boolean(),
      additional: z.boolean(),
      displayPriority: z.number(),
      separation: z.boolean(),
      slug: z.string().optional(),
      nameParts: z
        .array(
          z.object({
            type: z.string(),
            value: z.string(),
            valueSpeech: z.string().optional(),
          }),
        )
        .optional(),
    }),
  ),
  additionalStops: z.array(StopSchema),
  canceledStops: z.array(StopSchema),
  messages: z.object({
    common: z.array(
      z.object({
        text: z.string(),
        locale: z.string(),
        type: z.string(),
        change: z.boolean(),
        important: z.boolean(),
        open: z.boolean(),
        links: z.array(
          z.object({
            type: z.string(),
            name: z.string(),
          }),
        ),
      }),
    ),
    delay: z.array(
      z.object({
        text: z.string(),
        locale: z.string(),
        type: z.string(),
        change: z.boolean(),
        important: z.boolean(),
        open: z.boolean(),
        links: z.array(
          z.object({
            type: z.string(),
            name: z.string(),
          }),
        ),
      }),
    ),
    cancelation: z.array(
      z.object({
        text: z.string(),
        locale: z.string(),
        type: z.string(),
        change: z.boolean(),
        important: z.boolean(),
        open: z.boolean(),
        links: z.array(
          z.object({
            type: z.string(),
            name: z.string(),
          }),
        ),
      }),
    ),
    destination: z.array(
      z.object({
        text: z.string(),
        locale: z.string(),
        type: z.string(),
        change: z.boolean(),
        important: z.boolean(),
        open: z.boolean(),
        links: z.array(
          z.object({
            type: z.string(),
            name: z.string(),
          }),
        ),
      }),
    ),
    via: z.array(
      z.object({
        text: z.string(),
        locale: z.string(),
        type: z.string(),
        change: z.boolean(),
        important: z.boolean(),
        open: z.boolean(),
        links: z.array(
          z.object({
            type: z.string(),
            name: z.string(),
          }),
        ),
      }),
    ),
  }),
  providesVehicleSequence: z.boolean(),
});

export type Entry = z.infer<typeof EntrySchema>;

const ResponseSchema = z.object({
  globalMessages: z.array(z.any()),
  entries: z.array(z.array(EntrySchema)),
});

export type Response = z.infer<typeof ResponseSchema>;

const SAMPLE_DATA: Response = {
  globalMessages: [],
  entries: [
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T20:34:00+02:00",
        timeDelayed: "2025-05-11T20:34:00+02:00",
        delayed: false,
        platform: "7A-C",
        platformSchedule: "7A-C",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "S 2",
        type: "CITY_TRAIN",
        kind: "default",
        journeyID: "20250511-5fde30c2-4c10-3eda-9ddf-da4e62d2d1b1",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8100017",
          name: "Attnang-Puchheim",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8101558",
            name: "Salzburg Kasern",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100929",
            name: "Hallwang-Elixhausen",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8100774",
            name: "Eugendorf",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8110427",
            name: "Seekirchen/Wallersee Stadt",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
          {
            evaNumber: "8100426",
            name: "Seekirchen am Wallersee",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
          },
          {
            evaNumber: "8101803",
            name: "Wallersee",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
          },
          {
            evaNumber: "8100594",
            name: "Weng b.Neumarkt",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
          },
          {
            evaNumber: "8100134",
            name: "Neumarkt am Wallersee",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
          },
          {
            evaNumber: "8100019",
            name: "Straßwalchen",
            canceled: false,
            additional: false,
            displayPriority: 9,
            separation: false,
          },
          {
            evaNumber: "8101332",
            name: "Oberhofen-Zell am Moos",
            canceled: false,
            additional: false,
            displayPriority: 10,
            separation: false,
          },
          {
            evaNumber: "8101377",
            name: "Pöndorf",
            canceled: false,
            additional: false,
            displayPriority: 11,
            separation: false,
          },
          {
            evaNumber: "8100018",
            name: "Frankenmarkt",
            canceled: false,
            additional: false,
            displayPriority: 12,
            separation: false,
          },
          {
            evaNumber: "8100508",
            name: "Vöcklamarkt",
            canceled: false,
            additional: false,
            displayPriority: 13,
            separation: false,
          },
          {
            evaNumber: "8101428",
            name: "Redl-Zipf",
            canceled: false,
            additional: false,
            displayPriority: 14,
            separation: false,
          },
          {
            evaNumber: "8101260",
            name: "Neukirchen-Gampern",
            canceled: false,
            additional: false,
            displayPriority: 15,
            separation: false,
          },
          {
            evaNumber: "8101670",
            name: "Timelkam",
            canceled: false,
            additional: false,
            displayPriority: 16,
            separation: false,
          },
          {
            evaNumber: "8100507",
            name: "Vöcklabruck",
            canceled: false,
            additional: false,
            displayPriority: 17,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T20:39:00+02:00",
        timeDelayed: "2025-05-11T20:39:00+02:00",
        delayed: false,
        platform: "",
        platformSchedule: "",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "3236",
        virtual: false,
        lineName: "WB 968",
        type: "INTER_REGIONAL_TRAIN",
        kind: "default",
        journeyID: "20250511-42dc37b8-0814-3f7f-b0a4-956f3f0012aa",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8098262",
          name: "München Hbf Gl.5-10",
          canceled: false,
          slug: "muenchen-hbf",
          nameParts: [
            {
              type: "default",
              value: "München Hbf",
              valueSpeech: "München Hauptbahnhof",
            },
          ],
        },
        viaStops: [
          {
            evaNumber: "8000320",
            name: "Rosenheim",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
            slug: "rosenheim",
            nameParts: [
              {
                type: "default",
                value: "Rosenheim",
              },
            ],
          },
          {
            evaNumber: "8000262",
            name: "München Ost",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
            slug: "muenchen-ost",
            nameParts: [
              {
                type: "default",
                value: "München Ost",
              },
            ],
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: false,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T20:42:00+02:00",
        timeDelayed: "2025-05-11T20:42:00+02:00",
        delayed: false,
        platform: "7D-F",
        platformSchedule: "7D-F",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "S 3",
        type: "CITY_TRAIN",
        kind: "default",
        journeyID: "20250511-8e19eb40-4766-3f90-9d4c-9aca20f7d943",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8000108",
          name: "Freilassing",
          canceled: false,
          slug: "freilassing",
          nameParts: [
            {
              type: "default",
              value: "Freilassing",
            },
          ],
        },
        viaStops: [
          {
            evaNumber: "8102052",
            name: "Salzburg Mülln-Altstadt",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8102048",
            name: "Salzburg Aiglhof",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8102045",
            name: "Salzburg Taxham Europark",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8102063",
            name: "Salzburg Liefering",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T20:55:00+02:00",
        timeDelayed: "2025-05-11T20:55:00+02:00",
        delayed: false,
        platform: "8B-C",
        platformSchedule: "8B-C",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "R 21",
        type: "REGIONAL_TRAIN",
        kind: "default",
        journeyID: "20250511-9e44a71f-72bb-39df-a638-a358d0b7c5bc",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8100241",
          name: "Friedburg",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8101558",
            name: "Salzburg Kasern",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100929",
            name: "Hallwang-Elixhausen",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8110427",
            name: "Seekirchen/Wallersee Stadt",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8100426",
            name: "Seekirchen am Wallersee",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
          {
            evaNumber: "8100594",
            name: "Weng b.Neumarkt",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
          },
          {
            evaNumber: "8100134",
            name: "Neumarkt am Wallersee",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
          },
          {
            evaNumber: "8100020",
            name: "Steindorf bei Straßwalchen",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
          },
          {
            evaNumber: "8102062",
            name: "Straßwalchen West",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T20:56:00+02:00",
        timeDelayed: "2025-05-11T20:56:00+02:00",
        delayed: false,
        platform: "3A-C",
        platformSchedule: "3D-F",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "RJX 868",
        type: "HIGH_SPEED_TRAIN",
        kind: "default",
        journeyID: "20250511-f56d9fd4-bda6-3f09-95ec-02a3736d102a",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8100108",
          name: "Innsbruck Hbf",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8100001",
            name: "Kufstein",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100099",
            name: "Wörgl Hbf",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8100102",
            name: "Jenbach",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Gleiswechsel: Heute auf Gleis {{0}} (geplant war Gleis {{1}})",
              locale: "de",
              type: "track-changed",
              change: true,
              important: false,
              open: false,
              links: [
                {
                  type: "track",
                  name: "3A-C",
                },
                {
                  type: "track",
                  name: "3D-F",
                },
              ],
            },
            {
              text: "Fahrradmitnahme reservierungspflichtig",
              locale: "de",
              type: "bicycle-reservation-required",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100414_D_1",
        timeSchedule: "2025-05-11T21:00:00+02:00",
        timeDelayed: "2025-05-11T21:00:00+02:00",
        delayed: false,
        platform: "",
        platformSchedule: "",
        timeType: "SCHEDULE",
        canceled: false,
        administrationID: "810007",
        virtual: false,
        lineName: "S 1",
        type: "CITY_TRAIN",
        kind: "default",
        journeyID: "20250511-52a2544a-a7b5-3607-b7cd-668d6d75948b",
        stopPlace: {
          evaNumber: "8100414",
          name: "Salzburg Hbf (Bahnsteige 11-12)",
          canceled: false,
        },
        arrivalOrDepartureId: "8100414_D_1",
        destination: {
          evaNumber: "8100298",
          name: "Lamprechtshausen",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8101476",
            name: "Salzburg Itzling",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100404",
            name: "Salzburg Maria Plain-Plainbrücke",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8100912",
            name: "Hagenau b.Salzburg",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8100456",
            name: "Bergheim b.Salzburg",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
          {
            evaNumber: "8101519",
            name: "Bergheim b.Salzburg Schlachthof",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
          },
          {
            evaNumber: "8100578",
            name: "Muntigl",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
          },
          {
            evaNumber: "8101527",
            name: "Siggerwiesen",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
          },
          {
            evaNumber: "8100214",
            name: "Anthering",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
          },
          {
            evaNumber: "8100604",
            name: "Acharting",
            canceled: false,
            additional: false,
            displayPriority: 9,
            separation: false,
          },
          {
            evaNumber: "8135419",
            name: "Pabing am Haunsberg",
            canceled: false,
            additional: false,
            displayPriority: 10,
            separation: false,
          },
          {
            evaNumber: "8101811",
            name: "Weitwörth-Nußdorf",
            canceled: false,
            additional: false,
            displayPriority: 11,
            separation: false,
          },
          {
            evaNumber: "8101309",
            name: "Oichtensiedlung",
            canceled: false,
            additional: false,
            displayPriority: 12,
            separation: false,
          },
          {
            evaNumber: "8101874",
            name: "Oberndorf b.Salzburg-Laufen",
            canceled: false,
            additional: false,
            displayPriority: 13,
            separation: false,
          },
          {
            evaNumber: "8100509",
            name: "Oberndorf b.Salzburg Bahnhof",
            canceled: false,
            additional: false,
            displayPriority: 14,
            separation: false,
          },
          {
            evaNumber: "8101821",
            name: "Ziegelhaiden",
            canceled: false,
            additional: false,
            displayPriority: 15,
            separation: false,
          },
          {
            evaNumber: "8101913",
            name: "Arnsdorf b.Lamprechtshausen",
            canceled: false,
            additional: false,
            displayPriority: 16,
            separation: false,
          },
          {
            evaNumber: "8100217",
            name: "Bürmoos",
            canceled: false,
            additional: false,
            displayPriority: 17,
            separation: false,
          },
          {
            evaNumber: "8101817",
            name: "Zehmemoos",
            canceled: false,
            additional: false,
            displayPriority: 18,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: false,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:00:00+02:00",
        timeDelayed: "2025-05-11T21:00:00+02:00",
        delayed: false,
        platform: "3A-C",
        platformSchedule: "3A-C",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "55",
        virtual: false,
        lineName: "RJX 68",
        type: "HIGH_SPEED_TRAIN",
        kind: "default",
        journeyID: "20250511-e5c17c24-9bea-3c0d-9dad-03b60b91a35f",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8000261",
          name: "München Hbf",
          canceled: false,
          slug: "muenchen-hbf",
          nameParts: [
            {
              type: "default",
              value: "München Hbf",
              valueSpeech: "München Hauptbahnhof",
            },
          ],
        },
        viaStops: [
          {
            evaNumber: "8000320",
            name: "Rosenheim",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
            slug: "rosenheim",
            nameParts: [
              {
                type: "default",
                value: "Rosenheim",
              },
            ],
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Zwischen Freilassing und Traunstein finden Grenzkontrollen statt. Bitte halten Sie Ihren Reisepass oder Personalausweis bereit.",
              locale: "de",
              type: "general-warning",
              change: true,
              important: false,
              open: false,
              links: [],
            },
            {
              text: "Fahrradmitnahme reservierungspflichtig",
              locale: "de",
              type: "bicycle-reservation-required",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:07:00+02:00",
        timeDelayed: "2025-05-11T21:07:00+02:00",
        delayed: false,
        platform: "4",
        platformSchedule: "4",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "RJX 663",
        type: "HIGH_SPEED_TRAIN",
        kind: "default",
        journeyID: "20250511-b38568f3-3274-351e-bb54-deedd71111f7",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8103000",
          name: "Wien Hbf",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8100013",
            name: "Linz Hbf",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100008",
            name: "St.Pölten Hbf",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8100514",
            name: "Wien Meidling",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme reservierungspflichtig",
              locale: "de",
              type: "bicycle-reservation-required",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:08:00+02:00",
        timeDelayed: "2025-05-11T21:08:00+02:00",
        delayed: false,
        platform: "6",
        platformSchedule: "",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "M8",
        virtual: false,
        lineName: "RE 5",
        type: "REGIONAL_TRAIN",
        kind: "default",
        journeyID: "20250511-9f20315d-7b98-3cc2-9c85-8640f0d2902c",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8098262",
          name: "München Hbf Gl.5-10",
          canceled: false,
          slug: "muenchen-hbf",
          nameParts: [
            {
              type: "default",
              value: "München Hbf",
              valueSpeech: "München Hauptbahnhof",
            },
          ],
        },
        viaStops: [
          {
            evaNumber: "8000108",
            name: "Freilassing",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
            slug: "freilassing",
            nameParts: [
              {
                type: "default",
                value: "Freilassing",
              },
            ],
          },
          {
            evaNumber: "8005833",
            name: "Teisendorf",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
            slug: "teisendorf",
            nameParts: [
              {
                type: "default",
                value: "Teisendorf",
              },
            ],
          },
          {
            evaNumber: "8000116",
            name: "Traunstein",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
            slug: "traunstein",
            nameParts: [
              {
                type: "default",
                value: "Traunstein",
              },
            ],
          },
          {
            evaNumber: "8000888",
            name: "Bergen(Oberbay)",
            canceled: false,
            additional: false,
            displayPriority: 12,
            separation: false,
            slug: "bergen-oberbay",
            nameParts: [
              {
                type: "default",
                value: "Bergen ",
              },
              {
                type: "region",
                value: "(Oberbay)",
                valueSpeech: "(Oberbayern)",
              },
            ],
          },
          {
            evaNumber: "8005940",
            name: "Übersee",
            canceled: false,
            additional: false,
            displayPriority: 9,
            separation: false,
            slug: "uebersee",
            nameParts: [
              {
                type: "default",
                value: "Übersee",
              },
            ],
          },
          {
            evaNumber: "8000911",
            name: "Bernau a Chiemsee",
            canceled: false,
            additional: false,
            displayPriority: 10,
            separation: false,
            slug: "bernau-a-chiemsee",
            nameParts: [
              {
                type: "default",
                value: "Bernau ",
              },
              {
                type: "region",
                value: "a Chiemsee",
                valueSpeech: "am Chiemsee",
              },
            ],
          },
          {
            evaNumber: "8004885",
            name: "Prien a Chiemsee",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
            slug: "prien-am-chiemsee",
            nameParts: [
              {
                type: "default",
                value: "Prien ",
              },
              {
                type: "region",
                value: "am Chiemsee",
              },
            ],
          },
          {
            evaNumber: "8001787",
            name: "Bad Endorf",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
            slug: "bad-endorf-oberbay",
            nameParts: [
              {
                type: "default",
                value: "Bad Endorf ",
                valueSpeech: "Ba​d Endorf ",
              },
              {
                type: "region",
                value: "(Oberbay)",
                valueSpeech: "(Oberbayern)",
              },
            ],
          },
          {
            evaNumber: "8000320",
            name: "Rosenheim",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
            slug: "rosenheim",
            nameParts: [
              {
                type: "default",
                value: "Rosenheim",
              },
            ],
          },
          {
            evaNumber: "8002424",
            name: "Großkarolinenfeld",
            canceled: false,
            additional: false,
            displayPriority: 13,
            separation: false,
            slug: "grosskarolinenfeld",
            nameParts: [
              {
                type: "default",
                value: "Großkarolinenfeld",
              },
            ],
          },
          {
            evaNumber: "8004703",
            name: "Ostermünchen",
            canceled: false,
            additional: false,
            displayPriority: 14,
            separation: false,
            slug: "ostermuenchen",
            nameParts: [
              {
                type: "default",
                value: "Ostermünchen",
              },
            ],
          },
          {
            evaNumber: "8000634",
            name: "Aßling(Oberbay)",
            canceled: false,
            additional: false,
            displayPriority: 11,
            separation: false,
            slug: "assling-oberbay",
            nameParts: [
              {
                type: "default",
                value: "Aßling ",
              },
              {
                type: "region",
                value: "(Oberbay)",
                valueSpeech: "(Oberbayern)",
              },
            ],
          },
          {
            evaNumber: "8002347",
            name: "Grafing Bahnhof",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
            slug: "grafing-bahnhof",
            nameParts: [
              {
                type: "default",
                value: "Grafing Bahnhof",
              },
            ],
          },
          {
            evaNumber: "8000262",
            name: "München Ost",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
            slug: "muenchen-ost",
            nameParts: [
              {
                type: "default",
                value: "München Ost",
              },
            ],
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: false,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:08:00+02:00",
        timeDelayed: "2025-05-11T21:08:00+02:00",
        delayed: false,
        platform: "",
        platformSchedule: "",
        timeType: "SCHEDULE",
        canceled: false,
        administrationID: "8013D",
        virtual: false,
        lineName: "RB 45",
        type: "REGIONAL_TRAIN",
        kind: "default",
        journeyID: "20250511-f9a9a77d-ccc9-320c-8fd9-ac934c1258c2",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8000258",
          name: "Mühldorf(Oberbay)",
          canceled: false,
          slug: "muehldorf-oberbay",
          nameParts: [
            {
              type: "default",
              value: "Mühldorf ",
            },
            {
              type: "region",
              value: "(Oberbay)",
              valueSpeech: "(Oberbayern)",
            },
          ],
        },
        viaStops: [
          {
            evaNumber: "8102052",
            name: "Salzburg Mülln-Altstadt",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8102045",
            name: "Salzburg Taxham Europark",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8000108",
            name: "Freilassing",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
            slug: "freilassing",
            nameParts: [
              {
                type: "default",
                value: "Freilassing",
              },
            ],
          },
          {
            evaNumber: "8003584",
            name: "Laufen(Oberbay)",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
            slug: "laufen-oberbay",
            nameParts: [
              {
                type: "default",
                value: "Laufen ",
              },
              {
                type: "region",
                value: "(Oberbay)",
                valueSpeech: "(Oberbayern)",
              },
            ],
          },
          {
            evaNumber: "8003263",
            name: "Kirchanschöring",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
            slug: "kirchanschoering",
            nameParts: [
              {
                type: "default",
                value: "Kirchanschöring",
              },
            ],
          },
          {
            evaNumber: "8002097",
            name: "Fridolfing",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
            slug: "fridolfing",
            nameParts: [
              {
                type: "default",
                value: "Fridolfing",
              },
            ],
          },
          {
            evaNumber: "8006422",
            name: "Tittmoning-Wiesmühl",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
            slug: "tittmoning-wiesmuehl",
            nameParts: [
              {
                type: "default",
                value: "Tittmoning-Wiesmühl",
              },
            ],
          },
          {
            evaNumber: "8002184",
            name: "Garching(Alz)",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
            slug: "garching-alz",
            nameParts: [
              {
                type: "default",
                value: "Garching ",
              },
              {
                type: "region",
                value: "(Alz)",
              },
            ],
          },
          {
            evaNumber: "8005923",
            name: "Tüßling",
            canceled: false,
            additional: false,
            displayPriority: 9,
            separation: false,
            slug: "tuessling",
            nameParts: [
              {
                type: "default",
                value: "Tüßling",
              },
            ],
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:11:00+02:00",
        timeDelayed: "2025-05-11T21:11:00+02:00",
        delayed: false,
        platform: "5A-B",
        platformSchedule: "5A-B",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "RJ 843",
        type: "HIGH_SPEED_TRAIN",
        kind: "default",
        journeyID: "20250511-acb6527f-e425-3b2f-9629-19cf2b6ad257",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8103000",
          name: "Wien Hbf",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8100134",
            name: "Neumarkt am Wallersee",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100507",
            name: "Vöcklabruck",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8100017",
            name: "Attnang-Puchheim",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8100014",
            name: "Wels Hbf",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
          {
            evaNumber: "8100013",
            name: "Linz Hbf",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
          },
          {
            evaNumber: "8100009",
            name: "St. Valentin",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
          },
          {
            evaNumber: "8100012",
            name: "Amstetten NÖ",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
          },
          {
            evaNumber: "8100008",
            name: "St.Pölten Hbf",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
          },
          {
            evaNumber: "8102059",
            name: "Tullnerfeld",
            canceled: false,
            additional: false,
            displayPriority: 9,
            separation: false,
          },
          {
            evaNumber: "8100514",
            name: "Wien Meidling",
            canceled: false,
            additional: false,
            displayPriority: 10,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme reservierungspflichtig",
              locale: "de",
              type: "bicycle-reservation-required",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:12:00+02:00",
        timeDelayed: "2025-05-11T21:12:00+02:00",
        delayed: false,
        platform: "2",
        platformSchedule: "2",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "IC 794",
        type: "INTERCITY_TRAIN",
        kind: "default",
        journeyID: "20250511-e1506c07-7f05-32c3-8c02-bab29924e8dc",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8100044",
          name: "Schwarzach-St.Veit",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8101917",
            name: "Salzburg Süd",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100040",
            name: "Hallein",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8100546",
            name: "Kuchl",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8100041",
            name: "Golling-Abtenau",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
          {
            evaNumber: "8100539",
            name: "Werfen",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
          },
          {
            evaNumber: "8100042",
            name: "Bischofshofen",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
          },
          {
            evaNumber: "8100043",
            name: "St. Johann im Pongau",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme reservierungspflichtig",
              locale: "de",
              type: "bicycle-reservation-required",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:16:00+02:00",
        timeDelayed: "2025-05-11T21:16:00+02:00",
        delayed: false,
        platform: "9B-C",
        platformSchedule: "9B-C",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "REX 21",
        type: "REGIONAL_TRAIN",
        kind: "default",
        journeyID: "20250511-d38d8eee-70ff-31ee-94a7-718b42d2ab1a",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8100489",
          name: "Munderfing",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8100426",
            name: "Seekirchen am Wallersee",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100134",
            name: "Neumarkt am Wallersee",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8100020",
            name: "Steindorf bei Straßwalchen",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8102062",
            name: "Straßwalchen West",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
          {
            evaNumber: "8100241",
            name: "Friedburg",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
          },
          {
            evaNumber: "8102009",
            name: "Lengau",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
          },
          {
            evaNumber: "8101658",
            name: "Teichstätt",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
          },
          {
            evaNumber: "8100602",
            name: "Achenlohe",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:18:00+02:00",
        timeDelayed: "2025-05-11T21:18:00+02:00",
        delayed: false,
        platform: "1",
        platformSchedule: "3",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "NJ 468",
        type: "INTERCITY_TRAIN",
        kind: "default",
        journeyID: "20250511-d29e3f06-7597-3296-b62e-8df526a018e8",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8700011",
          name: "Paris Est",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8000320",
            name: "Rosenheim",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
            slug: "rosenheim",
            nameParts: [
              {
                type: "default",
                value: "Rosenheim",
              },
            ],
          },
          {
            evaNumber: "8000262",
            name: "München Ost",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
            slug: "muenchen-ost",
            nameParts: [
              {
                type: "default",
                value: "München Ost",
              },
            ],
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Zwischen Freilassing und Traunstein finden Grenzkontrollen statt. Bitte halten Sie Ihren Reisepass oder Personalausweis bereit.",
              locale: "de",
              type: "general-warning",
              change: true,
              important: false,
              open: false,
              links: [],
            },
            {
              text: "Gleiswechsel: Heute auf Gleis {{0}} (geplant war Gleis {{1}})",
              locale: "de",
              type: "track-changed",
              change: true,
              important: false,
              open: false,
              links: [
                {
                  type: "track",
                  name: "1",
                },
                {
                  type: "track",
                  name: "3",
                },
              ],
            },
            {
              text: "Reservierungspflicht",
              locale: "de",
              type: "reservation-required",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:18:00+02:00",
        timeDelayed: "2025-05-11T21:18:00+02:00",
        delayed: false,
        platform: "1",
        platformSchedule: "",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "NJ 40468",
        type: "INTERCITY_TRAIN",
        kind: "default",
        journeyID: "20250511-eb2139bb-e5fe-3a4e-b157-012fa915a468",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8800004",
          name: "Bruxelles Midi",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8000320",
            name: "Rosenheim",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
            slug: "rosenheim",
            nameParts: [
              {
                type: "default",
                value: "Rosenheim",
              },
            ],
          },
          {
            evaNumber: "8000262",
            name: "München Ost",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
            slug: "muenchen-ost",
            nameParts: [
              {
                type: "default",
                value: "München Ost",
              },
            ],
          },
          {
            evaNumber: "8000240",
            name: "Mainz Hbf",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
            slug: "mainz-hbf",
            nameParts: [
              {
                type: "default",
                value: "Mainz Hbf",
                valueSpeech: "Mainz Hauptbahnhof",
              },
            ],
          },
          {
            evaNumber: "8001083",
            name: "Bonn-Beuel",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
            slug: "bonn-beuel",
            nameParts: [
              {
                type: "city",
                value: "Bonn",
              },
              {
                type: "city-separator",
                value: "-",
              },
              {
                type: "default",
                value: "Beuel",
              },
            ],
          },
          {
            evaNumber: "8000207",
            name: "Köln Hbf",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
            slug: "koeln-hbf",
            nameParts: [
              {
                type: "default",
                value: "Köln Hbf",
                valueSpeech: "Köln Hauptbahnhof",
              },
            ],
          },
          {
            evaNumber: "8000001",
            name: "Aachen Hbf",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
            slug: "aachen-hbf",
            nameParts: [
              {
                type: "default",
                value: "Aachen Hbf",
                valueSpeech: "Aachen Hauptbahnhof",
              },
            ],
          },
          {
            evaNumber: "8800012",
            name: "Liège-Guillemins",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
          },
          {
            evaNumber: "8800002",
            name: "Bruxelles-Nord",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Zwischen Freilassing und Traunstein finden Grenzkontrollen statt. Bitte halten Sie Ihren Reisepass oder Personalausweis bereit.",
              locale: "de",
              type: "general-warning",
              change: true,
              important: false,
              open: false,
              links: [],
            },
            {
              text: "Reservierungspflicht",
              locale: "de",
              type: "reservation-required",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:21:00+02:00",
        timeDelayed: "2025-05-11T21:21:00+02:00",
        delayed: false,
        platform: "7A-C",
        platformSchedule: "7A-C",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "S 3",
        type: "CITY_TRAIN",
        kind: "default",
        journeyID: "20250511-2369bc3d-2f5f-38af-a548-cb74af088926",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8100044",
          name: "Schwarzach-St.Veit",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8102055",
            name: "Salzburg Sam",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100559",
            name: "Salzburg Gnigl",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8101481",
            name: "Salzburg Parsch",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8101470",
            name: "Salzburg Aigen",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
          {
            evaNumber: "8101917",
            name: "Salzburg Süd",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
          },
          {
            evaNumber: "8100772",
            name: "Elsbethen",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
          },
          {
            evaNumber: "8102054",
            name: "Puch b.Hallein Urstein",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
          },
          {
            evaNumber: "8101406",
            name: "Puch bei Hallein",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
          },
          {
            evaNumber: "8102006",
            name: "Oberalm",
            canceled: false,
            additional: false,
            displayPriority: 9,
            separation: false,
          },
          {
            evaNumber: "8100040",
            name: "Hallein",
            canceled: false,
            additional: false,
            displayPriority: 10,
            separation: false,
          },
          {
            evaNumber: "8102049",
            name: "Hallein Burgfried",
            canceled: false,
            additional: false,
            displayPriority: 11,
            separation: false,
          },
          {
            evaNumber: "8101718",
            name: "Bad Vigaun",
            canceled: false,
            additional: false,
            displayPriority: 12,
            separation: false,
          },
          {
            evaNumber: "8102047",
            name: "Kuchl Garnei",
            canceled: false,
            additional: false,
            displayPriority: 13,
            separation: false,
          },
          {
            evaNumber: "8100546",
            name: "Kuchl",
            canceled: false,
            additional: false,
            displayPriority: 14,
            separation: false,
          },
          {
            evaNumber: "8100041",
            name: "Golling-Abtenau",
            canceled: false,
            additional: false,
            displayPriority: 15,
            separation: false,
          },
          {
            evaNumber: "8101660",
            name: "Tenneck",
            canceled: false,
            additional: false,
            displayPriority: 16,
            separation: false,
          },
          {
            evaNumber: "8100539",
            name: "Werfen",
            canceled: false,
            additional: false,
            displayPriority: 17,
            separation: false,
          },
          {
            evaNumber: "8101353",
            name: "Pfarrwerfen",
            canceled: false,
            additional: false,
            displayPriority: 18,
            separation: false,
          },
          {
            evaNumber: "8100042",
            name: "Bischofshofen",
            canceled: false,
            additional: false,
            displayPriority: 19,
            separation: false,
          },
          {
            evaNumber: "8101219",
            name: "Mitterberghütten",
            canceled: false,
            additional: false,
            displayPriority: 20,
            separation: false,
          },
          {
            evaNumber: "8100043",
            name: "St. Johann im Pongau",
            canceled: false,
            additional: false,
            displayPriority: 21,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100414_D_1",
        timeSchedule: "2025-05-11T21:30:00+02:00",
        timeDelayed: "2025-05-11T21:30:00+02:00",
        delayed: false,
        platform: "",
        platformSchedule: "",
        timeType: "SCHEDULE",
        canceled: false,
        administrationID: "810007",
        virtual: false,
        lineName: "S 1",
        type: "CITY_TRAIN",
        kind: "default",
        journeyID: "20250511-28612bd1-ffbe-3c59-b545-4a25b16bc4ef",
        stopPlace: {
          evaNumber: "8100414",
          name: "Salzburg Hbf (Bahnsteige 11-12)",
          canceled: false,
        },
        arrivalOrDepartureId: "8100414_D_1",
        destination: {
          evaNumber: "8100298",
          name: "Lamprechtshausen",
          canceled: false,
        },
        viaStops: [
          {
            evaNumber: "8101476",
            name: "Salzburg Itzling",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8100404",
            name: "Salzburg Maria Plain-Plainbrücke",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8100912",
            name: "Hagenau b.Salzburg",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8100456",
            name: "Bergheim b.Salzburg",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
          {
            evaNumber: "8101519",
            name: "Bergheim b.Salzburg Schlachthof",
            canceled: false,
            additional: false,
            displayPriority: 5,
            separation: false,
          },
          {
            evaNumber: "8100578",
            name: "Muntigl",
            canceled: false,
            additional: false,
            displayPriority: 6,
            separation: false,
          },
          {
            evaNumber: "8101527",
            name: "Siggerwiesen",
            canceled: false,
            additional: false,
            displayPriority: 7,
            separation: false,
          },
          {
            evaNumber: "8100214",
            name: "Anthering",
            canceled: false,
            additional: false,
            displayPriority: 8,
            separation: false,
          },
          {
            evaNumber: "8100604",
            name: "Acharting",
            canceled: false,
            additional: false,
            displayPriority: 9,
            separation: false,
          },
          {
            evaNumber: "8135419",
            name: "Pabing am Haunsberg",
            canceled: false,
            additional: false,
            displayPriority: 10,
            separation: false,
          },
          {
            evaNumber: "8101811",
            name: "Weitwörth-Nußdorf",
            canceled: false,
            additional: false,
            displayPriority: 11,
            separation: false,
          },
          {
            evaNumber: "8101309",
            name: "Oichtensiedlung",
            canceled: false,
            additional: false,
            displayPriority: 12,
            separation: false,
          },
          {
            evaNumber: "8101874",
            name: "Oberndorf b.Salzburg-Laufen",
            canceled: false,
            additional: false,
            displayPriority: 13,
            separation: false,
          },
          {
            evaNumber: "8100509",
            name: "Oberndorf b.Salzburg Bahnhof",
            canceled: false,
            additional: false,
            displayPriority: 14,
            separation: false,
          },
          {
            evaNumber: "8101821",
            name: "Ziegelhaiden",
            canceled: false,
            additional: false,
            displayPriority: 15,
            separation: false,
          },
          {
            evaNumber: "8101913",
            name: "Arnsdorf b.Lamprechtshausen",
            canceled: false,
            additional: false,
            displayPriority: 16,
            separation: false,
          },
          {
            evaNumber: "8100217",
            name: "Bürmoos",
            canceled: false,
            additional: false,
            displayPriority: 17,
            separation: false,
          },
          {
            evaNumber: "8101817",
            name: "Zehmemoos",
            canceled: false,
            additional: false,
            displayPriority: 18,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: false,
      },
    ],
    [
      {
        canceledStopsAfterActualDestination: [],
        direction: "departure",
        id: "8100002_D_1",
        timeSchedule: "2025-05-11T21:32:00+02:00",
        timeDelayed: "2025-05-11T21:32:00+02:00",
        delayed: false,
        platform: "2D-F",
        platformSchedule: "2D-F",
        timeType: "PREVIEW",
        canceled: false,
        administrationID: "81",
        virtual: false,
        lineName: "S 2",
        type: "CITY_TRAIN",
        kind: "default",
        journeyID: "20250511-b0c9c1ba-3b24-34b6-bd92-01402f6b4b5f",
        stopPlace: {
          evaNumber: "8100002",
          name: "Salzburg Hbf",
          canceled: false,
        },
        arrivalOrDepartureId: "8100002_D_1",
        destination: {
          evaNumber: "8000108",
          name: "Freilassing",
          canceled: false,
          slug: "freilassing",
          nameParts: [
            {
              type: "default",
              value: "Freilassing",
            },
          ],
        },
        viaStops: [
          {
            evaNumber: "8102052",
            name: "Salzburg Mülln-Altstadt",
            canceled: false,
            additional: false,
            displayPriority: 1,
            separation: false,
          },
          {
            evaNumber: "8102048",
            name: "Salzburg Aiglhof",
            canceled: false,
            additional: false,
            displayPriority: 2,
            separation: false,
          },
          {
            evaNumber: "8102045",
            name: "Salzburg Taxham Europark",
            canceled: false,
            additional: false,
            displayPriority: 3,
            separation: false,
          },
          {
            evaNumber: "8102063",
            name: "Salzburg Liefering",
            canceled: false,
            additional: false,
            displayPriority: 4,
            separation: false,
          },
        ],
        additionalStops: [],
        canceledStops: [],
        messages: {
          common: [
            {
              text: "Fahrradmitnahme begrenzt möglich",
              locale: "de",
              type: "bicycle-transport",
              change: false,
              important: false,
              open: false,
              links: [],
            },
          ],
          delay: [],
          cancelation: [],
          destination: [],
          via: [],
        },
        providesVehicleSequence: true,
      },
    ],
  ],
};
